# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsonfind < Formula
  desc "jf prints out dotted paths to the given value for a given json file"
  homepage "https://afox.dev/posts/jsonfind"
  version "1.0.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wtfox/jsonfind/releases/download/v1.0.2/jsonfind_1.0.2_Darwin_x86_64.tar.gz"
    sha256 "fdbe4a5da0becd2e927076b15516366f91f265496e64ad077f97ac55b424fbd4"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/wtfox/jsonfind/releases/download/v1.0.2/jsonfind_1.0.2_Darwin_arm64.tar.gz"
    sha256 "c9ec671c91dddadbe8090143bba0811fa79e019bcf43e887fa7a3b2c8ca4a9d5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wtfox/jsonfind/releases/download/v1.0.2/jsonfind_1.0.2_Linux_x86_64.tar.gz"
    sha256 "d549f24b82495a0b8f90925bbafe473420c13a143fa0dbb0365223d55d712069"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wtfox/jsonfind/releases/download/v1.0.2/jsonfind_1.0.2_Linux_arm64.tar.gz"
    sha256 "ea2f3d9ced3ff2579681af28d974dd8ecf80feddf9c56b3b2fd56b636a6248a1"
  end

  def install
    bin.install "jsonfind"
    ...
  end

  test do
    system "#{bin}/jsonfind --help"
    ...
  end
end
