# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsonfind < Formula
  desc "jf prints out dotted paths to the given value for a given json file"
  homepage "https://afox.dev/posts/jsonfind"
  version "1.0.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wtfox/jsonfind/releases/download/v1.0.2/jsonfind_1.0.2_Darwin_x86_64.tar.gz"
    sha256 "cdfe141fbb5586851197cc38eb201ffbba4ecbee946e520a7d95ac2e4def8d51"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/wtfox/jsonfind/releases/download/v1.0.2/jsonfind_1.0.2_Darwin_arm64.tar.gz"
    sha256 "ebe977f226bfe3770f235f6fccaf1254ee40a129ca3956c3c8fa58966b3eae89"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wtfox/jsonfind/releases/download/v1.0.2/jsonfind_1.0.2_Linux_x86_64.tar.gz"
    sha256 "3ad5e1121129a7d1701878550239da144531036254e21f4f6a6c46dd86630594"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wtfox/jsonfind/releases/download/v1.0.2/jsonfind_1.0.2_Linux_arm64.tar.gz"
    sha256 "34646e229982c2d68f6e777f7183e67a86fc24ecc092c98e05451aa62a0fb0e4"
  end

  def install
    bin.install "jsonfind" => "jf"
  end

  test do
    system "#{bin}/jf --help"
  end
end
